/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsSentRouteImport } from './routes/cards-sent'
import { Route as CoinsRouteImport } from './routes/coins'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as CoinCoinIdRouteImport } from './routes/coin.$coinId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsSentRoute = CardsSentRouteImport.update({
  id: '/cards-sent',
  path: '/cards-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsRoute = CoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinCoinIdRoute = CoinCoinIdRouteImport.update({
  id: '/coin/$coinId',
  path: '/coin/$coinId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards-sent': typeof CardsSentRoute
  '/coins': typeof CoinsRoute
  '/launch': typeof LaunchRoute
  '/coin/$coinId': typeof CoinCoinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards-sent': typeof CardsSentRoute
  '/coins': typeof CoinsRoute
  '/launch': typeof LaunchRoute
  '/coin/$coinId': typeof CoinCoinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards-sent': typeof CardsSentRoute
  '/coins': typeof CoinsRoute
  '/launch': typeof LaunchRoute
  '/coin/$coinId': typeof CoinCoinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cards-sent' | '/coins' | '/launch' | '/coin/$coinId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cards-sent' | '/coins' | '/launch' | '/coin/$coinId'
  id: '__root__' | '/' | '/cards-sent' | '/coins' | '/launch' | '/coin/$coinId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsSentRoute: typeof CardsSentRoute
  CoinsRoute: typeof CoinsRoute
  LaunchRoute: typeof LaunchRoute
  CoinCoinIdRoute: typeof CoinCoinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards-sent': {
      id: '/cards-sent'
      path: '/cards-sent'
      fullPath: '/cards-sent'
      preLoaderRoute: typeof CardsSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins': {
      id: '/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$coinId': {
      id: '/coin/$coinId'
      path: '/coin/$coinId'
      fullPath: '/coin/$coinId'
      preLoaderRoute: typeof CoinCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsSentRoute: CardsSentRoute,
  CoinsRoute: CoinsRoute,
  LaunchRoute: LaunchRoute,
  CoinCoinIdRoute: CoinCoinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
